dev(hansbug): add walk method for FastTreeValue class
opendilab/treevalue pull request #28
Opened 2022-01-09 06:18 UTC by HansBug

## Description

As the title saied.

## Check List

- [ ] merge the latest version source branch/repo, and resolve all the conflicts
- [ ] pass style check
- [ ] pass all the tests

2022-01-26 09:35 UTC, PaParaZz1 requested changes

2022-01-26 09:35 UTC, PaParaZz1 commented on test/tree/general/base.py
> +        def test_walk(self):
add an argument for walk to indicate the layer of traverse

2022-01-29 03:12 UTC, HansBug commented
Some problems:
1. When the `depth` is given, and `include_nodes` is False, some treevalue object (tree node) will not be appeared. Is this ok?
2. I think that `flatten` function is designed not, maybe the default value of `include_nodes` can be set to `True`. The `flatten` function is used to flatten values, and walk is used to iterate all the nodes. Do you think this is ok? If yes, you need to check the existing code due to the change of default value.

2022-02-22 11:52 UTC, PaParaZz1 approved these changes

2022-02-22 11:53 UTC, merged